Update plugin, author information
easydigitaldownloads/edd-gravity-forms-checkout pull request #12
Opened 2021-04-13 14:11 UTC by robincornett

#9

2021-04-13 16:43 UTC, LisaCee reviewed
I'm not sure if we should handle this here or if I should make a new issue, but I searched "Katz" looking for any sneaky places we might have missed and there are a few dead links throughout the code to his support site.

2021-04-13 17:47 UTC, robincornett commented
Nice catch! I'm also wondering if we need to keep the `tmp` and `docs` directories--maybe a separate issue.

2021-04-13 18:24 UTC, LisaCee approved these changes

2021-04-14 09:20 UTC, ashleyfae requested changes
One tiny change, but otherwise looks good.

2021-04-14 09:20 UTC, ashleyfae commented on composer.json
> +  "name": "easydigitaldownloads/EDD-Gravity-Forms-Checkout",
```suggestion
  "name": "easydigitaldownloads/edd-gravity-forms-checkout",
```

To match the spacing in our repo name.

2021-04-14 10:23 UTC, ashleyfae approved these changes

2021-04-14 10:23 UTC, merged